#+TITLE: Recipe Manager Readme and Planning Doc

* Overview
Recipe Manager is an application that manages recipes and potentially your pantry

* Goals
** Core Goals
- Manages and tracks recipes
- Allows for tracking of pantry stock based on submitted recipes
- Automates grocery listings 
- Can be leveraged for budgeting or dieting
- Calorie balancer: Submenu/mode for tracking calories based on recipes 

** Auxillary Goals
- Barcode integration:
  may require hosting own database, probably not affordable
- Cross Platform:
  leverage react native front end to allow for web ui and app ui
- Further Automation: Automate grocery ordering or dieting/meal enabling based on scheduled meals and events
- Workout/calorie deficit tracker

* High Level Concepts
- Recipe Bank
- Stock: Pantry stock that you intend to use with recipe bank
- Cooking Handler/Helper: Some method of initiating a recipe and firing off neccessary tasks. Modularity is key for making this extensible. I am not opposed to plugin system.

* Tasks
** Frontend                                     :@computer:@development:
*** TODO Create general Fresh/Preact layout                       :@planning:
Need to decide what bits need to be islands. Fresh and deno will only send HTML to clients when possible, so deciding where we need to hydrate the client with js vs where we want to load api prior to generation is important for project structure. 
*** TODO Design basic recipe card component
Examine [[https://schema.org/Recipe][Recipe Schema]] and develop reusable recipe card component around it
** Backend
*** TODO Consider Deployment                                      :@planning:
Try to leverage deno to deploy fully wrapped app. See what’s feasible, postgre, json storage, consider potential mobile plans.
*** TODO Spin up basic web API implementing recipe schema 
Use [[https://schema.org/Recipe][Recipe Schema]] to allow some application to do CRUD operations on a set of recipes

